### ISSUE TITLE
Request to sublicense WorldUnsafeGetBlockMixin.class

### ISSUE THREAD

**Issue by repo-alt** [GTMEGA/Blendtronic#3]
Looks like WorldUnsafeGetBlockMixin would be a better fix than what we currently have

**Comment by SirFell** [comment]
[GTMEGA organization](https://github.com/GTMEGA) represented by [SirFell](https://github.com/SirFell) hereby grants [repo-alt](https://github.com/repo-alt) an exclusive, non-transferable license and right to use of [WorldUnsafeGetBlockMixin.class](https://github.com/GTMEGA/Blendtronic/blob/main/src/main/java/com/github/gtmega/blendtronic/mixins/minecraft/WorldUnsafeGetBlockMixin.java) as a part of [Hodgepodge](https://github.com/GTNewHorizons/Hodgepodge) until further notice. This permission notice shall be included in all copies of [WorldUnsafeGetBlockMixin.class](https://github.com/GTMEGA/Blendtronic/blob/main/src/main/java/com/github/gtmega/blendtronic/mixins/minecraft/WorldUnsafeGetBlockMixin.java).
